name: Automatic run
on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Comment the run
        run: echo "Automatically runned"
