name: Viewer Automation Tests
on:
  #this allows action to be calle from other action
  workflow_call:
  #this allows to run manually
  workflow_dispatch:
    inputs:
      Env:
        description: Environment to run
        default: dev
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Comment the run
        run: echo "Manually runned"
